<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\Account\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DriveFleet.Domain\DriveFleet.Domain.csproj" />
  </ItemGroup>

</Project>
