// <auto-generated />
using System;
using DriveFleet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveFleet.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DriveFleetDbContext))]
    [Migration("20260906005733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriveFleet.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.EmailConfirmationToken", b =>
                {
                    b.Property<int>("EmailConfirmationTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailConfirmationTokenId"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmailConfirmationTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmationTokens", (string)null);
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Extra", b =>
                {
                    b.Property<int>("ExtraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ExtraId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Extras", null, t =>
                        {
                            t.HasCheckConstraint("CK_Extras_Price", "[Price] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ExtraId = 1,
                            Active = true,
                            Description = "Portable GPS navigation system.",
                            Name = "GPS",
                            Price = 8.00m
                        },
                        new
                        {
                            ExtraId = 2,
                            Active = true,
                            Description = "Child safety seat for the rental vehicle.",
                            Name = "Baby Seat",
                            Price = 6.00m
                        },
                        new
                        {
                            ExtraId = 3,
                            Active = true,
                            Description = "Portable Wi-Fi hotspot for internet access during the rental.",
                            Name = "Portable Wi-Fi",
                            Price = 10.00m
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasswordResetTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("ReservationStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_TotalValue", "[TotalValue] >= 0");
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("ReservationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReservationStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReservationStatus", (string)null);

                    b.HasData(
                        new
                        {
                            ReservationStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            ReservationStatusId = 2,
                            Name = "Active"
                        },
                        new
                        {
                            ReservationStatusId = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            ReservationStatusId = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationVehicle", b =>
                {
                    b.Property<int>("ReservationVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationVehicleId"));

                    b.Property<decimal>("DailyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ReservationVehicleId");

                    b.HasIndex("ReservationId", "VehicleId")
                        .IsUnique();

                    b.HasIndex("VehicleId", "StartDate", "EndDate");

                    b.ToTable("ReservationVehicles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReservationVehicles_DailyPrice", "[DailyPrice] >= 0");

                            t.HasCheckConstraint("CK_ReservationVehicles_Dates", "[EndDate] > [StartDate]");
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationVehicleExtra", b =>
                {
                    b.Property<int>("ReservationVehicleExtraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationVehicleExtraId"));

                    b.Property<int>("ExtraId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservationVehicleId")
                        .HasColumnType("int");

                    b.HasKey("ReservationVehicleExtraId");

                    b.HasIndex("ExtraId");

                    b.HasIndex("ReservationVehicleId", "ExtraId")
                        .IsUnique();

                    b.ToTable("ReservationVehicleExtras", null, t =>
                        {
                            t.HasCheckConstraint("CK_RVE_Price", "[Price] >= 0");

                            t.HasCheckConstraint("CK_RVE_Quantity", "[Quantity] >= 1");
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ReservationVehicleId")
                        .HasColumnType("int");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReservationVehicleId")
                        .IsUnique();

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Stars", "[Stars] >= 1 AND [Stars] <= 5");
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Employee"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("VehicleStatusId");

                    b.ToTable("Vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_DailyPrice", "[DailyPrice] >= 0");

                            t.HasCheckConstraint("CK_Vehicles_Seats", "[Seats] > 0");
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.VehicleStatus", b =>
                {
                    b.Property<int>("VehicleStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleStatus", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleStatusId = 1,
                            Name = "Available"
                        },
                        new
                        {
                            VehicleStatusId = 2,
                            Name = "Reserved"
                        },
                        new
                        {
                            VehicleStatusId = 3,
                            Name = "Unavailable"
                        });
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.EmailConfirmationToken", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.User", "User")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.ReservationStatus", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveFleet.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReservationStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationVehicle", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ReservationVehicles")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveFleet.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ReservationVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationVehicleExtra", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.Extra", "Extra")
                        .WithMany("ReservationVehicleExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveFleet.Domain.Entities.ReservationVehicle", "ReservationVehicle")
                        .WithMany("ReservationVehicleExtras")
                        .HasForeignKey("ReservationVehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Extra");

                    b.Navigation("ReservationVehicle");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Review", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.ReservationVehicle", "ReservationVehicle")
                        .WithOne("Review")
                        .HasForeignKey("DriveFleet.Domain.Entities.Review", "ReservationVehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReservationVehicle");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.User", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("DriveFleet.Domain.Entities.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DriveFleet.Domain.Entities.VehicleStatus", "VehicleStatus")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Extra", b =>
                {
                    b.Navigation("ReservationVehicleExtras");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("ReservationVehicles");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.ReservationVehicle", b =>
                {
                    b.Navigation("ReservationVehicleExtras");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ReservationVehicles");
                });

            modelBuilder.Entity("DriveFleet.Domain.Entities.VehicleStatus", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
